### ISSUE TITLE
Test Case 

### ISSUE THREAD

**Issue by paul-rogers-dev** [sibtc/django-beginners-guide#1]
class LoginRequiredPasswordChangeTests(TestCase):
    def test_redirection(self):
        url = reverse('password_change')
        login_url = reverse('login')
        response = self.client.get(url)
        self.assertRedirects(response, **f**'{login_url}?next={url}')

Noticed this causes test to fail and in PyCharm the miscellaneous 'f' highlights file in red.

**Comment by vitorfs** [comment]
Hi Paul,

It's a `f-string`, new in Python 3.6
https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals

Perhaps it would be equivalent to doing `'{login_url}?next={url}'.format(login_url=login_url, url=url)`
I guess it would be a good idea to change it, to avoid breaking on older versions of Python

**Comment by paul-rogers-dev** [comment]
Ah yes, 3.6. Have PyCharm running 3.5 on a System76 laptop with Ubuntu and the latest I can install is 3.5 Thanks for the reply.
